name: Build

on:
  workflow_call:
  push:
    branches:
      - main
      - dev

jobs:
  checks:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Swift format lint
        run: swift format lint -r src --strict

  build:
    needs: checks
    runs-on: macos-latest

    strategy:
      fail-fast: false
      matrix:
        arch: [x86_64, arm64]

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Build and package DMG
        run: |
          npm install --global create-dmg
          make dmg-${{ matrix.arch }}
